[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "schnetpack"
# Declaring that the version will be read dynamically.
# This helps us not having to specify the version twice.
# We have to specify the version only in schnetpack.__version__
# see [tool.setuptools.dynamic] below
dynamic = ["version"]
authors = [
    { name = "Kristof T. Schuett" },
    { name = "Michael Gastegger" },
    { name = "Stefaan Hessmann" },
    { name = "Niklas Gebauer" },
    { name = "Jonas Lederer" }
]
description = "SchNetPack - Deep Neural Networks for Atomistic Systems"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.10"
dependencies = [

]

[project.optional-dependencies]
test = ["pytest", "pytest-datadir", "pytest-benchmark"]

[tool.setuptools]
package-dir = { "" = "src" }
script-files = [
    "src/scripts/spkconvert",
    "src/scripts/spktrain",
    "src/scripts/spkpredict",
    "src/scripts/spkmd",
    "src/scripts/spkdeploy",
]

[tool.setuptools.dynamic]
version = {attr = "schnetpack.__version__"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
schnetpack = ["configs/**/*.yaml"]
